#!/usr/bin/env node
// Host rendered videos at a public https URL so Instagram can fetch them.
//
// WHY THIS EXISTS
// Instagram does not accept file uploads on the Instagram Login path. It cURLs
// the video from a URL you hand it, so the MP4 must be publicly reachable at
// the moment of publishing. Without this step Instagram publishing cannot work
// at all.
//
// WHY GITHUB RELEASES
// Considered and rejected:
//   Commit MP4s to the repo   ~3MB x 5/day = ~5GB/year of permanent history.
//   Vercel static hosting     same problem, the files must be in the repo.
//   Workflow artifacts        require auth to download, so Instagram cannot
//                             fetch them. This is the trap: they look public.
//   Vercel Blob / S3          works, but adds a paid dependency and secrets.
//
// Release assets are public on a public repo, free, unlimited in practice, do
// not bloat the git history, and the gh CLI is already available in CI.
//
// IMPORTANT: this relies on the repo being PUBLIC. If bbmw0-technologies-ai is
// ever made private, release assets start requiring auth and Instagram will
// fail to fetch. The preflight below checks for exactly that.
//
// USAGE:
//   node scripts/publish-media.mjs --date=2026-07-26
//   node scripts/publish-media.mjs --date=2026-07-26 --dry-run
//
// OUTPUT: writes daily/<date>/media-urls.json mapping slug to public URL,
//         and prints PUBLIC_MEDIA_BASE_URL=... for the calling shell.
//
// EXIT CODES: 0 hosted, 1 bad arguments, 2 hosting failed

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { execSync } from "node:child_process";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");

function readJSON(p, fallback) {
  try { return JSON.parse(fs.readFileSync(p, "utf8").replace(/^﻿/, "")); }
  catch (e) { if (fallback !== undefined) return fallback; throw e; }
}

function args(argv) {
  const o = {};
  for (const a of argv.slice(2)) {
    if (a.startsWith("--")) {
      const eq = a.indexOf("=");
      if (eq === -1) o[a.slice(2)] = true;
      else o[a.slice(2, eq)] = a.slice(eq + 1);
    }
  }
  return o;
}
const A = args(process.argv);
const DATE = A.date || new Date().toISOString().slice(0, 10);
const DRY = !!A["dry-run"];

const REPO = process.env.MEDIA_REPO || "bbmw96/bbmw0-technologies-ai";
const TAG = `media-${DATE}`;

const dir = path.join(ROOT, "daily", DATE);
if (!fs.existsSync(dir)) { console.error(`No daily/${DATE}/ directory.`); process.exit(1); }

const sh = (cmd, opts = {}) =>
  execSync(cmd, { cwd: ROOT, encoding: "utf8", stdio: ["inherit", "pipe", "pipe"], ...opts });

// Only videos actually destined for a platform that needs public hosting.
const metas = fs.readdirSync(dir).filter((f) => f.endsWith(".meta.json"))
  .map((f) => ({ slug: f.replace(/\.meta\.json$/, ""), meta: readJSON(path.join(dir, f)) }));

const needsHosting = metas.filter((m) => m.meta.platform === "instagram");
if (!needsHosting.length) {
  console.log("No Instagram-destined videos for this date. Nothing to host.");
  process.exit(0);
}

// Preflight: a private repo silently breaks this, and the failure surfaces
// later as an opaque Instagram fetch error. Catch it here instead.
try {
  const vis = sh(`gh repo view ${REPO} --json isPrivate --jq .isPrivate`).trim();
  if (vis === "true") {
    console.error(`FATAL: ${REPO} is private. Release assets on a private repo require`);
    console.error("authentication, so Instagram cannot fetch them. Either make the repo");
    console.error("public or set PUBLIC_MEDIA_BASE_URL to a CDN you control.");
    process.exit(2);
  }
} catch (err) {
  console.error(`Could not check repo visibility: ${err.message}`);
  process.exit(2);
}

const missing = needsHosting.filter((m) => !fs.existsSync(path.join(ROOT, m.meta.file)));
if (missing.length) {
  console.error(`Not rendered yet: ${missing.map((m) => m.slug).join(", ")}`);
  process.exit(1);
}

const base = `https://github.com/${REPO}/releases/download/${TAG}`;

if (DRY) {
  console.log(`[dry run] would host ${needsHosting.length} file(s) under ${base}`);
  needsHosting.forEach((m) => console.log(`  ${path.basename(m.meta.file)}`));
  process.exit(0);
}

try {
  // Idempotent: reuse the release if a previous run created it.
  let exists = true;
  try { sh(`gh release view ${TAG} --repo ${REPO}`); }
  catch { exists = false; }

  if (!exists) {
    sh(`gh release create ${TAG} --repo ${REPO} --title "Media ${DATE}" ` +
       `--notes "Rendered Shorts for ${DATE}, hosted so Instagram can fetch them. Generated by scripts/publish-media.mjs."`);
    console.log(`Created release ${TAG}`);
  } else {
    console.log(`Reusing release ${TAG}`);
  }

  const urls = {};
  for (const { slug, meta } of needsHosting) {
    const file = path.join(ROOT, meta.file);
    const name = path.basename(file);
    // --clobber so a re-render replaces the asset rather than erroring.
    sh(`gh release upload ${TAG} "${file}" --repo ${REPO} --clobber`);
    urls[slug] = `${base}/${encodeURIComponent(name)}`;
    console.log(`  hosted ${name}`);
  }

  fs.writeFileSync(path.join(dir, "media-urls.json"),
    JSON.stringify({ date: DATE, repo: REPO, tag: TAG, base, urls }, null, 2) + "\n");

  console.log(`\nPUBLIC_MEDIA_BASE_URL=${base}`);
  console.log(`Wrote daily/${DATE}/media-urls.json`);
  process.exit(0);
} catch (err) {
  console.error(`Hosting failed: ${err.stderr || err.message || err}`);
  process.exit(2);
}
